### ISSUE TITLE
Missing release / version number for review

### ISSUE THREAD

**Issue by krother** [DataScienceInPractice/Site#4]
On https://github.com/openjournals/jose-reviews/issues/121 a release is mentioned as part of the review checklist. I suggest creating one on https://github.com/DataScienceInPractice/Site/tags and labeling it `v1.0` or similar.

**Comment by TomDonoghue** [comment]
Thanks for the note @krother - I have now made a release tag for the current version of the project:
https://github.com/DataScienceInPractice/Site/releases/tag/1.0
