### ISSUE TITLE
Mismatching licenses in repository and JOSE paper

### ISSUE THREAD

**Issue by krother** [DataScienceInPractice/Site#6]
Hi @TomDonoghue ,

during the JOSE review https://github.com/openjournals/jose-reviews/issues/121 I discovered that your paper references the CC-BY 4.0 license, while the repository references CC-NC-BY 4.0. Both are approved OSI licenses, but I think they should be consistent.

**Comment by TomDonoghue** [comment]
Hey @krother - thanks for the note, that was our bad on the discrepancy! I have updated and consolidated to use and list the CC-BY 4.0 license across the board.
